### ISSUE TITLE
Examples of tasks / plugins using streams

### ISSUE THREAD

**Issue by backflip** [nfroidure/gulp-streamify#4]
Hey Nicolas,
what would be a good example of a plugin using streams? I'm currently under the impression that most frontend-related tasks (dealing with JS, CSS, media files etc.) absolutely need the complete file content to be buffered to be able to do their work.

**Comment by backflip** [comment]
gulp-svgicons2svgfont is mentioned in https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/dealing-with-streams.md but it seems to be buffering the files, too: https://github.com/nfroidure/gulp-svgicons2svgfont/blob/master/src/index.js#L35

I see that prepending content to a file works fine without buffering, however, I don't really see many other use cases.

**Comment by nfroidure** [comment]
Hi!

The function you point out is a mistake. It should be named 'queueFiles' or whatever.

gulp-svgicons2svgfont doesn't change the internal file contents, it is done by the svgicons2svgfont module.

It just queue file streams in order to transmit them to svgicons2svgfont since it has design flaws as it ask them as an array instead of getting them on the fly.

But, the files content is still read/parsed by using streams and the font is streamed out.

You can see that i'm buffering file contents here but only if the files in were bufferred as the Gulp guidelines wants. https://github.com/nfroidure/gulp-svgicons2svgfont/blob/master/src/index.js#L127

My point is that there is a stream ready implementation for every format that can be tranformed without knowing all the file contents in advance. XML, CSV, HTML and most file formats allow it.

Formats that doesn't allow streaming are, imo, bad design. So goes JSON, MIDI (format 2) by example,

browserify is another good example of streams usage. Also hinters, filters, append/preprenders, mergers gulp plugins should be streamable IMO (see my gulp-insert, gulp-spawn patches).

Also, streams aren't easy to implement, that is the reason why you often find libraries that doesn't deal with them.

My point is to support streams when possible, even if i have to admit it isn't the point of every developpers.

I wrote gulp-streamify for that matter after an attempt to include a stream/buffer automatic switch in the gulp core https://github.com/wearefractal/vinyl/pull/4

**Comment by backflip** [comment]
I totally agree on this being a reasonable best practice, however, I did not see that many use cases. After discovering [sax](https://www.npmjs.com/package/sax) in your [svgicons2svgfont](https://github.com/nfroidure/svgicons2svgfont/blob/master/src/index.js#L57), I might see some more. Wouldn't JSON be "stream ready" the same way?

How would a hinter work without buffering the complete file (or at least "logical units")?

**Comment by nfroidure** [comment]
JSON need to be fully parsed to ensure it is syntaxically ok. Also it is not really made to be parsed and exploited that way. But you're right, you could try to stream them.

For hinters, the answer is in your question ;). They read the file contents, convert it in an AST tree and then compute it to detect problems. Once read, you do not need the file contents so keeping a buffer in memory is useless.

Most transformations aren't mad on the content himself but on an internal representation of that contents. For CSV, you often manipulate an object or an array representing the string like here https://github.com/SimpliField/oh-csv#transforming-csv-on-the-fly. In this cas, keeping the buffer means keeping the information twice.

So needing to have the whole content, doesn't mean you need to have it raw in a buffer.

**Comment by backflip** [comment]
So instead of buffering the whole file you would read chunk by chunk and try to make sense of it. In case of JavaScript you might look for curly braces to find blocks of code and create an AST. Is this correct? If so: Is this reasonable when dealing with JavaScript and CSS files, e.g., since they usually have file sizes below 100 kb? Seems to add a lot of complexity compared to creating the AST from a buffer.

**Comment by backflip** [comment]
An example might help me understand: What would be a more elegant solution for [gulp-resolve-dependencies](https://github.com/backflip/gulp-resolve-dependencies)? I'm currently doing a string search on the file's buffered content. In case of a match, I'm using ```fs.readFileSync``` to read the content of the matched path and create a new vinyl file from it, which is prepended to the stream and searched for matches itself. While this sounds inefficient in about every way imaginable, I'm not sure about alternatives. For one thing, judging from [replacestream](https://github.com/eugeneware/replacestream/blob/master/index.js) and [streamsearch](https://github.com/mscdex/streamsearch/blob/master/lib/sbmh.js), searching for strings in a stream sounds pretty difficult.

**Comment by nfroidure** [comment]
Applying a search on a complete buffer requires per nature to be able to buffer the whole content. You still can stream since when an occurence is found, you can pass the previously buffered content through and then having an optimal usage of system ressources.

This is why grep processes files line per line.

This is also why most of the file formats/communication protocols uses headers in order to add metadatas to a file and be able to read them without consuming the whole stream. The files of your Gulp plugin could be considered like a file format with headers.

You could consume the stream until you find */ and just pass the file through since you don't really need those lines if you minify your assets then. For debugging puprose, you also could unshift datas to the stream, see http://nodejs.org/api/stream.html#stream_readable_unshift_chunk .

On the complexity, i totally agree. But modern development implies 100% tests coveraging (especially for libraries/modules) and allow complexity to be easily managed.

On the parser paticular case, parsing on the fly add a very tiny layer of complexity since parsing means reading char by char which is the nature of streaming (a char is a n bytes length chunk).

**Comment by nfroidure** [comment]
So if you're wondering why i think anyone should support streaming when possible, it is due to my root programming principle: "Who can do more, can do less". It particularly apply to streams since it can be buffered at any time if needed.

**Comment by backflip** [comment]
1. This sounds very reasonable.
2. Thanks a lot for taking the time!
